name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install sdl2
      run: sudo apt update && sudo apt install git libsdl2-dev
    - name: see what is inside
      run: ls -al
    - name: make
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
       name: yay
       path: ./project
       if-no-files-found: warn
